### ISSUE TITLE
how 2 run this on windows 8??

### ISSUE THREAD

**Issue by williamyeny** [JoshuaRLi/interjection.sh#1]
pls 2 help, need 2 meme

**Comment by JerryMcLinux** [comment]
This is an .sh script. It can only be run on UNIX/Linux systems. Run it on a mac, or in a GNU/Linux VM.

**Comment by williamyeny** [comment]
need help, how 2 convert windows to Linus? need to download converter?

**Comment by JoshuaRLi** [comment]
@williamyeny [Cygwin](https://www.cygwin.com/) will give you a UNIX-like environment on Windows, but this script currently doesn't support Cygwin's package manager (PR's welcome!)
